package org.activityinfo.theme.client;

import com.google.gwt.core.client.GWT;
import com.google.gwt.resources.client.ClientBundle;
import com.google.gwt.resources.client.TextResource;

public interface Resources extends ClientBundle {

    final Resources RESOURCES = GWT.create(Resources.class);

    /**
     * Generated by gulp
     */
    @Source("app.css")
    TextResource styles();
}
